stages:
    - build
    - test
    - namespaces
    - secrets
    - system
    - certificates

variables:
    PROD_KUBECONFIG: prod-kubeconfig.yml
    RUNNER_IMAGE: registry.gitlab.com/startfleet/gitlab-runner:v1.1
before_script:
    - mkdir ~/.kube/
    - echo $KUBECONFIG_PROD | base64 -d > ~/.kube/config

## Templates ##
.test-template: &test-template
    stage: test
    image: $RUNNER_IMAGE
    tags:
        - startfleet
.deploy-template: &deploy-template
    image: $RUNNER_IMAGE
    when: manual
    tags:
        - startfleet

### Tests ###
namespaces-test:
    <<: *test-template
    script:
        - kubectl apply -f 03-Kubernetes/namespaces/hasura-namespace.yml --dry-run=true
        - kubectl apply -f 03-Kubernetes/namespaces/armadacar-namespace.yml --dry-run=true
        - kubectl apply -f 03-Kubernetes/namespaces/cert-manager-namespace.yml --dry-run=true
        - kubectl apply -f 03-Kubernetes/namespaces/keycloak-namespace.yml --dry-run=true

secrets-test:
    <<: *test-template
    script:
        - kubectl apply -f 03-Kubernetes/secrets/armadacar-regsecret.yml --dry-run=true
        - kubectl apply -f 03-Kubernetes/secrets/keycloak-secret.yml --dry-run=true

certificates-test:
    <<: *test-template
    script:
        - kubectl apply -f 03-Kubernetes/certificates/armadacar-crt.yml --dry-run=true
        - kubectl apply -f 03-Kubernetes/certificates/hasura-crt.yml --dry-run=true
        - kubectl apply -f 03-Kubernetes/certificates/keycloak-crt.yml --dry-run=true

### Deploy namespaces ###
armadacar-namespace:
    stage: namespaces
    <<: *deploy-template
    script:
        - kubectl apply -f 03-Kubernetes/namespaces/armadacar-namespace.yml
hasura-namespace:
    stage: namespaces
    <<: *deploy-template
    script:
        - kubectl apply -f 03-Kubernetes/namespaces/hasura-namespace.yml
cert-manager-namespace:
    stage: namespaces
    <<: *deploy-template
    script:
        - kubectl apply -f 03-Kubernetes/namespaces/cert-manager-namespace.yml
keycloak-namespace:
    stage: namespaces
    <<: *deploy-template
    script:
        - kubectl apply -f 03-Kubernetes/namespaces/keycloak-namespace.yml

### Deploy secrets ###
armadacar-secret:
    stage: secrets
    <<: *deploy-template
    script:
        - envsubst < 03-Kubernetes/secrets/armadacar-regsecret.yml > armadacar-regsecret.yml
        - kubectl apply -f armadacar-regsecret.yml
keycloak-secret:
    stage: secrets
    <<: *deploy-template
    script:
        - kubectl apply -f 03-Kubernetes/secrets/keycloak-secret.yml

### Deploy system ###
cert-manager:
    stage: system
    <<: *deploy-template
    script:
        - kubectl apply -f 03-Kubernetes/system/cert-manager.yaml
cluster-issuer:
    # step for the cluster issuer for the certificates bc the cert-manager webhook is long to start
    stage: system
    <<: *deploy-template
    script:
        - kubectl apply -f 03-Kubernetes/system/prod-issuer.yml

### Deploy certificates ###
hasura:
    stage: certificates
    <<: *deploy-template
    script: 
        - kubectl apply -f 03-Kubernetes/certificates/hasura-crt.yml
armadacar:
    stage: certificates
    <<: *deploy-template
    script: 
        - kubectl apply -f 03-Kubernetes/certificates/armadacar-crt.yml
keycloak:
    stage: certificates
    <<: *deploy-template
    script: 
        - kubectl apply -f 03-Kubernetes/certificates/keycloak-crt.yml