apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: keycloak-selfsigned-cert
  namespace: keycloak
spec:
  dnsNames:
    - login.startfleet.ovh
  secretName: keycloak-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer